name: Frontend - Static Site Quality

on:
  push:
    branches:
      - "**"
  pull_request:

permissions:
  contents: read

jobs:
  static-site-quality:
    name: Call reusable static site quality workflow
    uses: s5micheldevops/platform-reusable-workflows/.github/workflows/reusable-static-site-quality.yml@v0.1.0
